version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: local-sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./sql-init:/docker-entrypoint-initdb.d

  webapi:
    build: .
    container_name: game-recorder-api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=master;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "5000:80"

volumes:
  sqlserver-data: